// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/mahiro72/SPAJAM2022/server/infra/repository"
	"github.com/mahiro72/SPAJAM2022/server/presen/handler"
	"github.com/mahiro72/SPAJAM2022/server/usecase"
)

// Injectors from wire.go:

func InitTemplateHandler(driver *sql.DB) handler.TemplateHandler {
	iTemplateRepository := repository.NewTemplateRepository(driver)
	templateUsecase := usecase.NewTemplateUsecase(iTemplateRepository)
	templateHandler := handler.NewTemplateHandler(templateUsecase)
	return templateHandler
}

func InitDrinkHandler(driver *sql.DB) handler.DrinkHandler {
	iDrinkRepository := repository.NewDrinkRepository(driver)
	drinkUsecase := usecase.NewDrinkUsecase(iDrinkRepository)
	drinkHandler := handler.NewDrinkHandler(drinkUsecase)
	return drinkHandler
}
