// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/mahiro72/SPAJAM2022/server/infra/repository"
	"github.com/mahiro72/SPAJAM2022/server/presen/handler"
	"github.com/mahiro72/SPAJAM2022/server/usecase"
)

// Injectors from wire.go:

func InitDrinkHandler(driver *sql.DB) handler.DrinkHandler {
	iDrinkRepository := repository.NewDrinkRepository(driver)
	drinkUsecase := usecase.NewDrinkUsecase(iDrinkRepository)
	drinkHandler := handler.NewDrinkHandler(drinkUsecase)
	return drinkHandler
}

func InitFeedbackHandler(driver *sql.DB) handler.FeedbackHandler {
	iFeedbackRepository := repository.NewFeedbackRepository(driver)
	feedbackUsecase := usecase.NewFeedbackUsecase(iFeedbackRepository)
	feedbackHandler := handler.NewFeedbackHandler(feedbackUsecase)
	return feedbackHandler
}
