version: '3'
services:
  server:
    container_name: SPAJAM2022-server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    command: /bin/sh -c "go run main.go"
    env_file:
      ./server/server.env
    stdin_open: true
    tty: true
    volumes:
      - ./server:/app
    ports:
      - 8080:8080
    depends_on:
      - "db"

  db:
    container_name: SPAJAM2022-db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - ./db/db.env
    restart: always
